### PR TITLE
Upgrade to Roundcube v1.1.2

### PR DESCRIPTION
**Pull request by mburns**
The current default version `1.0.2` was released a full year ago.
- [x] unit tests pass
- [x] integration tests pass

### CODE REVIEW

**Comment by flaccid** [comment]
@mburns could you also updated the tests (https://github.com/xhost-cookbooks/roundcube/blob/master/test/unit/spec/install_spec.rb). It would be awesome if you could fix the other failed tests too while you're there :)

**Comment by mburns** [comment]
Happy to! I'll give it the ol' college try and see what I come up with.

**Comment by mburns** [comment]
@flaccid fixed in 7097269

**Comment by flaccid** [comment]
Thanks @mburns !

**Pull request merged**
